name: build-and-push-latest-docker-image

on:
  push:
    branches:
      - "master"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to quay.io
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_TOKEN }}
          registry: quay.io

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: exporter-go
          push: true
          tags: quay.io/kohlstechnology/opa_scorecard_exporter:latest
